version: "3.7"
services:
  db:
    build: ./api/db
  webserver:
    build: ./api/api
    depends_on:
      - db
    ports:
      - 5000:5000
  front:
    build: ./front
    depends_on:
      - webserver
    ports:
      - 80:80